// Mock data for clients
export const mockClients = [
  {
    id: '1',
    name: 'Trần Văn B',
    avatar: 'https://randomuser.me/api/portraits/men/32.jpg',
    email: 'tranvanb@email.com',
    phone: '0912345678',
    age: 28,
    gender: 'Nam',
    height: 175,
    weight: 70,
    goals: 'Tăng cơ, giảm mỡ và cải thiện sức khỏe tổng thể. Mục tiêu giảm 5kg trong 3 tháng.',
    medicalHistory: 'Không có bệnh lý đặc biệt',
    trainingHistory: 'Đã tập gym được 1 năm, chủ yếu tập cardio.',
    startDate: '15/03/2024',
    notes: 'Khách hàng nghiêm túc, có động lực cao'
  },
  {
    id: '2',
    name: 'Lê Thị C',
    avatar: 'https://randomuser.me/api/portraits/women/44.jpg',
    email: 'lethic@email.com',
    phone: '0923456789',
    age: 32,
    gender: 'Nữ',
    height: 162,
    weight: 55,
    goals: 'Tăng cường sức khỏe và dẻo dai, cải thiện tư thế.',
    medicalHistory: 'Từng bị chấn thương đầu gối nhẹ cách đây 2 năm',
    trainingHistory: 'Mới bắt đầu tập luyện',
    startDate: '05/04/2024',
    notes: 'Cần tập nhẹ nhàng, tăng dần cường độ'
  },
  {
    id: '3',
    name: 'Phạm Văn D',
    avatar: 'https://randomuser.me/api/portraits/men/67.jpg',
    email: 'phamvand@email.com',
    phone: '0934567890',
    age: 24,
    gender: 'Nam',
    height: 180,
    weight: 75,
    goals: 'Tập luyện để thi đấu thể hình nghiệp dư',
    medicalHistory: 'Không có',
    trainingHistory: 'Đã tập gym 3 năm, từng tham gia 1 cuộc thi cấp quận',
    startDate: '10/02/2024',
    notes: 'Yêu cầu chế độ tập cao cường độ, kèm chế độ ăn chi tiết'
  },
  {
    id: '4',
    name: 'Nguyễn Thị X',
    avatar: 'https://randomuser.me/api/portraits/women/22.jpg',
    email: 'nguyenthix@email.com',
    phone: '0945678901',
    age: 35,
    gender: 'Nữ',
    height: 165,
    weight: 62,
    goals: 'Giảm cân, tăng cường sự dẻo dai và thư giãn với yoga',
    medicalHistory: 'Có vấn đề về cột sống nhẹ',
    trainingHistory: 'Đã tập yoga tại nhà 6 tháng',
    startDate: '20/03/2024',
    notes: 'Lưu ý về các bài tập có tác động tới cột sống'
  },
  {
    id: '5',
    name: 'Trần Văn Y',
    avatar: 'https://randomuser.me/api/portraits/men/54.jpg',
    email: 'tranvany@email.com',
    phone: '0956789012',
    age: 22,
    gender: 'Nam',
    height: 178,
    weight: 68,
    goals: 'Tăng cân, phát triển cơ bắp',
    medicalHistory: 'Không có',
    trainingHistory: 'Mới bắt đầu tập',
    startDate: '01/05/2024',
    notes: 'Cần tư vấn dinh dưỡng kèm tập luyện'
  }
];
