services:
  app:
    build: .
    container_name: datn_be
    restart: always
    ports:
      - "9000:9000"
    volumes:
      - ./uploads:/uploads
    depends_on:
      - mysql
      - redis
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/gym_management?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root_password
      - SPRING_REDIS_HOST=redis
      - SPRING_REDIS_PORT=6379
    networks:
      - gym-network

  mysql:
    image: mysql:8.0
    container_name: datn_mysql
    restart: always
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root_password
      - MYSQL_DATABASE=gym_management
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    networks:
      - gym-network

  redis:
    image: redis:7.0-alpine
    container_name: datn_redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - gym-network

  # Có thể thêm phpmyadmin để quản lý cơ sở dữ liệu MySQL (tùy chọn)
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: datn_phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      - PMA_HOST=mysql
      - PMA_PORT=3306
    depends_on:
      - mysql
    networks:
      - gym-network

networks:
  gym-network:
    driver: bridge

volumes:
  mysql-data:
  redis-data:
  uploads: